[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sddmm_linear"
version = "0.0.1"

dependencies = [
    "torch>=2.6.0",
]

[tool.setuptools.packages.find]
where = ["src"]